---
- name: install mariadb
  yum:
    name: mariadb
    state: latest
- name: install mariadb server
  yum:
    name: mariadb-server
    state: latest
- name: install php_mysql
  yum:
    name: phpmql
    state: latest

- name: strart mariadb
  service:
    name: mariadb
    state: started