--- ### install httpd on Centos7
- hosts: masterhost
  become: true
  tasks:
    - name: install httpd on centos7
      yum:
       name: httpd
       state: latest           
       
    - name: start httpd service
      service: 
       name: httpd
       state: started
       
    - name: copy the webpage
      copy:
       src: index.html
       dest: /var/www/html
       
    - name: restart httpd service after copying index.html
      service:
       name: httpd
       state: restarted
      
      